USE [master]
GO

/****** Object:  Database [testarchdb]    Script Date: 03/02/2022 11:25:16 a. m. ******/
CREATE DATABASE [testarchdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testarchdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\testarchdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testarchdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\testarchdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testarchdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testarchdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testarchdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testarchdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testarchdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testarchdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [testarchdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testarchdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testarchdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testarchdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testarchdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testarchdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testarchdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testarchdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testarchdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testarchdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testarchdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testarchdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testarchdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testarchdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testarchdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testarchdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testarchdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testarchdb] SET RECOVERY FULL 
GO

ALTER DATABASE [testarchdb] SET  MULTI_USER 
GO

ALTER DATABASE [testarchdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testarchdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testarchdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testarchdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testarchdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testarchdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [testarchdb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [testarchdb] SET  READ_WRITE 
GO


